import {
  pgTable,
  uuid,
  varchar,
  text,
  boolean,
  integer,
  decimal,
  timestamp,
  jsonb,
  index,
  unique,
} from "drizzle-orm/pg-core";
import { relations } from "drizzle-orm";

// ==========================================
// USERS
// ==========================================

export const users = pgTable("users", {
  id: uuid("id").primaryKey().defaultRandom(),
  email: varchar("email", { length: 320 }).notNull().unique(),
  name: varchar("name", { length: 255 }),
  avatarUrl: text("avatar_url"),
  supabaseAuthId: uuid("supabase_auth_id").unique().notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

// ==========================================
// ORGANIZATIONS
// ==========================================

export const organizations = pgTable("organizations", {
  id: uuid("id").primaryKey().defaultRandom(),
  name: varchar("name", { length: 255 }).notNull(),
  slug: varchar("slug", { length: 100 }).notNull().unique(),
  ownerId: uuid("owner_id").notNull().references(() => users.id, { onDelete: "cascade" }),
  plan: varchar("plan", { length: 20 }).notNull().default("free"),
  paddleCustomerId: varchar("paddle_customer_id", { length: 255 }),
  paddleSubscriptionId: varchar("paddle_subscription_id", { length: 255 }),
  paddleSubscriptionStatus: varchar("paddle_subscription_status", { length: 50 }).default("none"),
  monthlyScanQuota: integer("monthly_scan_quota").notNull().default(100),
  monthlyScansUsed: integer("monthly_scans_used").notNull().default(0),
  quotaResetAt: timestamp("quota_reset_at", { withTimezone: true }).notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

// ==========================================
// CHATBOTS
// ==========================================

export const chatbots = pgTable(
  "chatbots",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    orgId: uuid("org_id").notNull().references(() => organizations.id, { onDelete: "cascade" }),
    name: varchar("name", { length: 255 }).notNull(),

    // Connection - MVP: api_endpoint + custom_webhook only
    connectionType: varchar("connection_type", { length: 30 }).notNull().default("api_endpoint"),
    endpointUrl: text("endpoint_url"),
    apiKeyEncrypted: text("api_key_encrypted"),
    requestTemplate: jsonb("request_template"),
    responsePath: varchar("response_path", { length: 500 }),
    headers: jsonb("headers").default({}),

    // Scan config
    scanFrequency: varchar("scan_frequency", { length: 20 }).notNull().default("daily"),
    nextScanAt: timestamp("next_scan_at", { withTimezone: true }),
    scanDelayMs: integer("scan_delay_ms").notNull().default(1500), // throttle: 1.5s between questions
    timeoutMs: integer("timeout_ms").notNull().default(30000),

    // Status
    isActive: boolean("is_active").notNull().default(true),
    lastScanAt: timestamp("last_scan_at", { withTimezone: true }),
    lastHealthScore: decimal("last_health_score", { precision: 5, scale: 2 }),
    consecutiveFailures: integer("consecutive_failures").notNull().default(0),

    // Metadata
    websiteUrl: text("website_url"),
    description: text("description"),

    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    index("idx_chatbots_org").on(table.orgId),
    index("idx_chatbots_next_scan").on(table.nextScanAt),
  ]
);

// ==========================================
// TEST CASES
// ==========================================

export const testCases = pgTable(
  "test_cases",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    chatbotId: uuid("chatbot_id").notNull().references(() => chatbots.id, { onDelete: "cascade" }),
    question: text("question").notNull(),
    expectedAnswer: text("expected_answer").notNull(),
    category: varchar("category", { length: 100 }),
    priority: varchar("priority", { length: 10 }).notNull().default("medium"),
    matchStrategy: varchar("match_strategy", { length: 30 }).notNull().default("semantic"),
    semanticThreshold: decimal("semantic_threshold", { precision: 3, scale: 2 }).notNull().default("0.70"),
    isAutoGenerated: boolean("is_auto_generated").notNull().default(false),
    generationSource: varchar("generation_source", { length: 50 }),
    isActive: boolean("is_active").notNull().default(true),
    lastScore: decimal("last_score", { precision: 5, scale: 2 }),
    lastTestedAt: timestamp("last_tested_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [index("idx_test_cases_chatbot").on(table.chatbotId)]
);

// ==========================================
// SCAN RUNS
// ==========================================

export const scanRuns = pgTable(
  "scan_runs",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    chatbotId: uuid("chatbot_id").notNull().references(() => chatbots.id, { onDelete: "cascade" }),
    orgId: uuid("org_id").notNull().references(() => organizations.id, { onDelete: "cascade" }),
    triggerType: varchar("trigger_type", { length: 20 }).notNull(),
    status: varchar("status", { length: 20 }).notNull().default("pending"),
    totalTests: integer("total_tests").notNull().default(0),
    passedTests: integer("passed_tests").notNull().default(0),
    failedTests: integer("failed_tests").notNull().default(0),
    errorTests: integer("error_tests").notNull().default(0),
    healthScore: decimal("health_score", { precision: 5, scale: 2 }),
    startedAt: timestamp("started_at", { withTimezone: true }),
    completedAt: timestamp("completed_at", { withTimezone: true }),
    durationMs: integer("duration_ms"),
    errorMessage: text("error_message"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    index("idx_scan_runs_chatbot").on(table.chatbotId),
    index("idx_scan_runs_status").on(table.status),
  ]
);

// ==========================================
// SCAN RESULTS
// ==========================================

export const scanResults = pgTable(
  "scan_results",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    scanRunId: uuid("scan_run_id").notNull().references(() => scanRuns.id, { onDelete: "cascade" }),
    testCaseId: uuid("test_case_id").notNull().references(() => testCases.id, { onDelete: "cascade" }),
    questionSent: text("question_sent").notNull(),
    actualAnswer: text("actual_answer"),
    expectedAnswer: text("expected_answer").notNull(),
    score: decimal("score", { precision: 5, scale: 2 }).notNull().default("0"),
    passed: boolean("passed").notNull().default(false),
    matchStrategy: varchar("match_strategy", { length: 30 }).notNull(),
    judgeReasoning: text("judge_reasoning"),
    judgeModel: varchar("judge_model", { length: 50 }),
    latencyMs: integer("latency_ms"),
    error: text("error"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [index("idx_scan_results_run").on(table.scanRunId)]
);

// ==========================================
// ALERT CONFIGS
// ==========================================

export const alertConfigs = pgTable("alert_configs", {
  id: uuid("id").primaryKey().defaultRandom(),
  chatbotId: uuid("chatbot_id").notNull().references(() => chatbots.id, { onDelete: "cascade" }),
  type: varchar("type", { length: 30 }).notNull(), // health_drop, drift_detected, endpoint_down, critical_failure
  channel: varchar("channel", { length: 20 }).notNull(), // email, slack
  destination: text("destination").notNull(), // email address or slack webhook URL
  threshold: decimal("threshold", { precision: 5, scale: 2 }),
  isActive: boolean("is_active").notNull().default(true),
  cooldownMinutes: integer("cooldown_minutes").notNull().default(60),
  lastTriggeredAt: timestamp("last_triggered_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

// ==========================================
// ALERT HISTORY
// ==========================================

export const alertHistory = pgTable("alert_history", {
  id: uuid("id").primaryKey().defaultRandom(),
  alertConfigId: uuid("alert_config_id").notNull().references(() => alertConfigs.id, { onDelete: "cascade" }),
  scanRunId: uuid("scan_run_id").references(() => scanRuns.id, { onDelete: "set null" }),
  message: text("message").notNull(),
  deliveryStatus: varchar("delivery_status", { length: 20 }).notNull().default("pending"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

// ==========================================
// RELATIONS
// ==========================================

export const usersRelations = relations(users, ({ many }) => ({
  organizations: many(organizations),
}));

export const organizationsRelations = relations(organizations, ({ one, many }) => ({
  owner: one(users, { fields: [organizations.ownerId], references: [users.id] }),
  chatbots: many(chatbots),
}));

export const chatbotsRelations = relations(chatbots, ({ one, many }) => ({
  organization: one(organizations, { fields: [chatbots.orgId], references: [organizations.id] }),
  testCases: many(testCases),
  scanRuns: many(scanRuns),
  alertConfigs: many(alertConfigs),
}));

export const testCasesRelations = relations(testCases, ({ one, many }) => ({
  chatbot: one(chatbots, { fields: [testCases.chatbotId], references: [chatbots.id] }),
  scanResults: many(scanResults),
}));

export const scanRunsRelations = relations(scanRuns, ({ one, many }) => ({
  chatbot: one(chatbots, { fields: [scanRuns.chatbotId], references: [chatbots.id] }),
  organization: one(organizations, { fields: [scanRuns.orgId], references: [organizations.id] }),
  results: many(scanResults),
}));

export const scanResultsRelations = relations(scanResults, ({ one }) => ({
  scanRun: one(scanRuns, { fields: [scanResults.scanRunId], references: [scanRuns.id] }),
  testCase: one(testCases, { fields: [scanResults.testCaseId], references: [testCases.id] }),
}));
